Controllers/AulasController.cs
using HealthUp.Data;
using HealthUp.Filters;
using HealthUp.Helpers;
using HealthUp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HealthUp.Controllers
{
    [MyRoleFilter(Perfil = "Admin")]
    public class AulasController : BaseController
    {
        private readonly HealthUpContext _context;
        private readonly IHostEnvironment _hostEnvironment;

        public AulasController(HealthUpContext context, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Aulas
        public async Task<IActionResult> Index()
        {
            Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<Aula, Admin> healthUpContext = _context.Aulas.Include(a => a.NumAdminNavigation).ThenInclude(a => a.NumAdminNavigation).Include(a => a.NumProfessorNavigation).ThenInclude(a => a.NumAdminNavigation);
            return View(await healthUpContext.ToListAsync());
        }


        // GET: Aulas/Create
        public IActionResult Create()
        {
            List<string> Horas = new List<string>();
            ViewData["NomeProfessor"] = new SelectList(_context.Professores.Include(x => x.NumProfessorNavigation), "NumProfessorNavigation.NumCC", "NumProfessorNavigation.Nome");
            List<string> dias = new List<string>() { "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira", "Sábado", "Domingo" };
            ViewData["DiaSemana"] = new SelectList(dias);
            Ginasio gym = _context.Ginasios.SingleOrDefault();
            int numero_aulas_diarias = Convert.ToInt32(((gym.Hora_Fecho.TotalMinutes - gym.Hora_Abertura.TotalMinutes)) / 50);
            int min_cont = (int)gym.Hora_Abertura.TotalMinutes;
            for (int i = 0; i < numero_aulas_diarias; i++)
            {
                // timespan do total de minutos
                Horas.Add(new TimeSpan(0, min_cont, 0).ToString(@"hh\:mm"));
                min_cont += 50;

            }
            ViewData["HorasInicio"] = new SelectList(Horas);
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestSizeLimit(100_000_000)]
        public IActionResult Create(IFormCollection dados, IFormFile FotografiaDivulgacao, IFormFile VideoDivulgacao)
        {


            Aula aula = new Aula
            {

                // Guardar o id do admin que criou
                NumAdmin = HttpContext.Session.GetString("UserId"),
                // Guardar o professor associado a esta aula
                NumProfessor = dados["IdProfessor"],
                // alterar
                DiaSemana = HelperFunctions.GetDay(dados["DiaSemana"]),

                HoraInicio = TimeSpan.Parse(dados["HoraInicio"] + ":00"),
                Lotacao = int.Parse(dados["Lotacao"]),
                ValidoDe = DateTime.Parse(dados["ValidoDe"]),
                ValidoAte = DateTime.Parse(dados["ValidoAte"]),
                Nome = dados["Nome"],
                Descricao = dados["Descricao"],
                FotografiaDivulgacao = Path.GetFileName(FotografiaDivulgacao.FileName),
                VideoDivulgacao = Path.GetFileName(VideoDivulgacao.FileName)
            };
            if (ModelState.IsValid)
            {


                _context.Add(aula);
                _context.SaveChanges();

                //guardar ficheiros no wwwroot
                string caminho = Path.Combine(_hostEnvironment.ContentRootPath, "wwwroot\\Ficheiros");
                string nome_ficheiro = Path.GetFileName(FotografiaDivulgacao.FileName);
                string caminho_completo = Path.Combine(caminho, nome_ficheiro);

                FileStream f = new FileStream(caminho_completo, FileMode.Create);
                FotografiaDivulgacao.CopyTo(f);

                f.Close();


                string caminho1 = Path.Combine(_hostEnvironment.ContentRootPath, "wwwroot\\Ficheiros");
                string nome_ficheiro1 = Path.GetFileName(VideoDivulgacao.FileName);
                string caminho_completo1 = Path.Combine(caminho1, nome_ficheiro1);

                FileStream ff = new FileStream(caminho_completo1, FileMode.Create);
                VideoDivulgacao.CopyTo(ff);

                ff.Close();

                return RedirectToAction(nameof(Index));

            }
            List<string> Horas = new List<string>();
            ViewData["NomeProfessor"] = new SelectList(_context.Professores.Include(x => x.NumProfessorNavigation), "NumProfessorNavigation.NumCC", "NumProfessorNavigation.Nome");
            List<string> dias = new List<string>() { "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira", "Sábado", "Domingo" };
            ViewData["DiaSemana"] = new SelectList(dias);
            Ginasio gym = _context.Ginasios.SingleOrDefault();
            int numero_aulas_diarias = Convert.ToInt32(((gym.Hora_Fecho.TotalMinutes - gym.Hora_Abertura.TotalMinutes)) / 50);
            int min_cont = (int)gym.Hora_Abertura.TotalMinutes;
            for (int i = 0; i < numero_aulas_diarias; i++)
            {
                // timespan do total de minutos
                Horas.Add(new TimeSpan(0, min_cont, 0).ToString(@"hh\:mm"));
                min_cont += 50;

            }
            ViewData["HorasInicio"] = new SelectList(Horas);

            return View(aula);
        }

        // GET: Aulas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Aula aula = await _context.Aulas.FindAsync(id);
            if (aula == null)
            {
                return NotFound();
            }
            List<string> Horas = new List<string>();
            ViewData["NumProfessor"] = new SelectList(_context.Professores, "NumCC", "NumCC", aula.NumProfessor);
            List<string> dias = new List<string>() { "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira", "Sábado", "Domingo" };
            ViewData["DiaSemana"] = new SelectList(dias);
            Ginasio gym = _context.Ginasios.SingleOrDefault();
            int numero_aulas_diarias = Convert.ToInt32(((gym.Hora_Fecho.TotalMinutes - gym.Hora_Abertura.TotalMinutes)) / 50);
            int min_cont = (int)gym.Hora_Abertura.TotalMinutes;
            for (int i = 0; i < numero_aulas_diarias; i++)
            {
                // timespan do total de minutos
                Horas.Add(new TimeSpan(0, min_cont, 0).ToString(@"hh\:mm"));
                min_cont += 50;

            }
            ViewData["HorasInicio"] = new SelectList(Horas);

            return View(aula);
        }

        // POST: Aulas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAula,Nome,NumProfessor,NumAdmin,ValidoDe,ValidoAte,Lotacao,HoraInicio,DiaSemana,FotografiaDivulgacao,VideoDivulgacao,Descricao")] Aula aula)
        {
            if (id != aula.IdAula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AulaExists(aula.IdAula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            List<string> Horas = new List<string>();
            ViewData["NumProfessor"] = new SelectList(_context.Professores, "NumCC", "NumCC", aula.NumProfessor);
            List<string> dias = new List<string>() { "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira", "Sábado", "Domingo" };
            ViewData["DiaSemana"] = new SelectList(dias);
            Ginasio gym = _context.Ginasios.SingleOrDefault();
            int numero_aulas_diarias = Convert.ToInt32(((gym.Hora_Fecho.TotalMinutes - gym.Hora_Abertura.TotalMinutes)) / 50);
            int min_cont = (int)gym.Hora_Abertura.TotalMinutes;
            for (int i = 0; i < numero_aulas_diarias; i++)
            {
                // timespan do total de minutos
                Horas.Add(new TimeSpan(0, min_cont, 0).ToString(@"hh\:mm"));
                min_cont += 50;

            }
            ViewData["HorasInicio"] = new SelectList(Horas);


            return View(aula);
        }

        // GET: Aulas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Aula aula = await _context.Aulas
                .Include(a => a.NumAdminNavigation).ThenInclude(a => a.NumAdminNavigation)
                .Include(a => a.NumProfessorNavigation).ThenInclude(a => a.NumProfessorNavigation)
                .FirstOrDefaultAsync(m => m.IdAula == id);
            if (aula == null)
            {
                return NotFound();
            }

            return View(aula);
        }

        // POST: Aulas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Aula aula = await _context.Aulas.FindAsync(id);

Views/Shared/Erro.cshtml
@{
    ViewData["Title"] = "Erro";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}

<div class="container">
    <h1 class="text-danger">Erro!</h1>
    <h2 class="text-danger">Occoreu um erro ao processar o seu pedido.</h2>

    <div>
        @ViewData["mensagem"]
    </div>
</div>

Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>@ViewData["Title"] - HealthUp</title>
    <!--Ícon do site-->
    <link rel="shortcut icon" type="image/x-icon" href="~/logoicon.ico" />

    <!--Fonte AweSome-->
    <script src="https://kit.fontawesome.com/210c3af75f.js" crossorigin="anonymous"></script>

    <!--Scrpit do gráfico para histórico de peso-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,500,600,700&display=swap" rel="stylesheet">

    <!--Estilo css-->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/mystyle.css" type="text/css">
</head>
<body>
    <header>
        @{
            var db = Context.RequestServices.GetRequiredService<HealthUpContext>();
            var mensagens = db.Mensagens.Include(m => m.IdPessoaReceiverNavigation).Include(m => m.IdPessoaSenderNavigation).Where(x => x.IdPessoaReceiver == Context.Session.GetString("UserId"));
            var MensagensNaoLidas = mensagens.Where(m => m.Lida == false).Count();
            var PedidosPendentesSocio = db.PedidosSocios.Count();
            var PedidosProfessor = db.SolicitacaoProfessores.Where(s=>s.NumAdmin==null).Count();
            var CotasAtraso = db.Cota.ToList().Where(c=>c.NumeroCotasNaoPagas!=0).Count();
            var NotificacoesAdmin = CotasAtraso + PedidosProfessor + PedidosPendentesSocio;
            var gym = db.Ginasios.SingleOrDefault();
        }
        <div class="logo">
            <a asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" width="70" height="70"></a>
        </div>
        <ul class="nav">
            <li><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
            <li><a asp-controller="Home" asp-action="Contactos">Contactos</a></li>
            <li><a asp-controller="Home" asp-action="MapaAulas">Mapa semanal de aulas</a></li>
            <li>
                @if (Context.Session.GetString("UserId") == null)
                {
                    <a asp-controller="Utilizadores" asp-action="PedidoSocio">Aderir</a>
                }
            </li>
            <li>
                @if (Context.Session.GetString("UserId") == null)
                {
                    <a asp-controller="Utilizadores" asp-action="Login">Entrar</a>
                }

                @if (Context.Session.GetString("Role") == "Socio")
                {
                    <a href="#">
                        Painel de sócios
                        @if (MensagensNaoLidas > 0)
                        {
                            <span>(@MensagensNaoLidas)</span>
                        }
                        <i class="fa fa-chevron-down" style="font-size: .8em;"></i>
                    </a>
                    <ul>
                        <li>
                            <a asp-controller="Mensagens" asp-action="CaixaEntrada">
                                Mensagens
                                @if (MensagensNaoLidas > 0)
                                {
                                    <span>(@MensagensNaoLidas)</span>
                                }
                            </a>
                        </li>
                        @{
                            var planos = db.PlanosTreino.Include(p => p.Contem).ThenInclude(cp => cp.IdExercicioNavigation).Include(p => p.NumProfessorNavigation).ThenInclude(p => p.NumProfessorNavigation).Include(p => p.NumSocioNavigation).ThenInclude(p => p.NumSocioNavigation).Where(p => p.NumSocio == Context.Session.GetString("UserId"));
                        }
                        @if (planos.Any() == true)
                        {
                            <li><a asp-controller="Socios" asp-action="ConsultarPlanoTreino">Plano de exercícios</a></li>
                        }
                        <li><a asp-controller="Socios" asp-action="ListarAulas"> Inscrição em aulas</a></li>
                        <li><a asp-controller="Socios" asp-action="ConsultarHistoricoPeso">Histórico de peso</a></li>
                        <li><a asp-controller="Socios" asp-action="HistoricoAulas">Histórico de aulas</a></li>
                        @if (Context.Session.GetString("ExistePT") == "Sim")
                        {
                            <li><a asp-controller="Socios" asp-action="ConsultarInfoPT">Consultar Informação do PT</a></li>
                        }
                        else
                        {
                            <li><a asp-controller="Socios" asp-action="SolicitarPT">Solicitar Personal Trainer</a></li>
                        }

                    </ul>
                }

                @if (Context.Session.GetString("Role") == "Professor")
                {
                    <a href="#">
                        Painel de professores
                        @if (MensagensNaoLidas > 0)
                        {
                            <span>(@MensagensNaoLidas)</span>
                        }
                        <i class="fa fa-chevron-down" style="font-size: .8em;"></i>
                    </a>
                    <ul>
                        <li>
                            <a asp-controller="Mensagens" asp-action="CaixaEntrada">
                                Mensagens
                                @if (MensagensNaoLidas > 0)
                                {
                                    <span>(@MensagensNaoLidas)</span>
                                }
                            </a>
                        </li>
                        <li><a asp-controller="Professores" asp-action="RegistarPesoSocio">Registar peso de sócio</a></li>
                        <li><a asp-controller="PlanoTreinos" asp-action="Index">Gerir plano de treinos</a></li>
                        <li><a asp-controller="Professores" asp-action="ConsultarAulasQueLeciona">Consultar aulas que leciono</a></li>
                        <li><a asp-controller="Professores" asp-action="ConsultarSociosInscritosAulas">Consultar sócios inscritos nas minhas aulas</a></li>
                        <li><a asp-controller="Professores" asp-action="ConsultarMeusAlunos">Consultar os meus alunos</a></li>
                    </ul>
                }

                @if (Context.Session.GetString("Role") == "Admin")
                {
                    <a href="#">
                        Painel de gestão
                        @if (NotificacoesAdmin > 0)
                        {
                            <span>(@NotificacoesAdmin)</span>
                        }
                        <i class="fa fa-chevron-down" style="font-size: .8em;"></i>
                    </a>
                    <ul>
                        <li>
                            <a asp-controller="Admins" asp-action="AprovarSocios">
                                Aprovar pedidos de sócio pendentes
                                @if (PedidosPendentesSocio > 0)
                                {
                                    <span>(@PedidosPendentesSocio)</span>
                                }
                            </a>
                        </li>
                        <li><a asp-controller="Admins" asp-action="GerirPessoas">Gerir pessoas </a></li>
                        <li>
                            <a asp-controller="Admins" asp-action="AprovarPedidoProf">
                                Aprovar pedidos de personal trainer
                                @if (PedidosProfessor > 0)
                                {
                                    <span>(@PedidosProfessor)</span>
                                }
                            </a>
                        </li>
                        <li><a asp-controller="Exercicios" asp-action="Index">Gerir exercícios</a></li>
                        <li><a asp-controller="Aulas" asp-action="Index">Gerir aulas</a></li>
                        <li><a asp-controller="Admins" asp-action="SuspenderUtilizador">Suspender utilizador</a></li>
                        <li>
                            <a asp-controller="Admins" asp-action="GerirCotas">
                                Gerir cotas
                                @if (CotasAtraso > 0)
                                {
                                    <span>(@CotasAtraso)</span>
                                }
                            </a>
                        </li>
                        <li><a asp-controller="Admins" asp-action="EditarInfoHealthUp">Editar informações do ginásio</a></li>
                    </ul>
                }
            </li>

            <li>
                @if (Context.Session.GetString("UserId") != null)
                {
                    <a asp-controller="Utilizadores" asp-action="Logout">Sair</a>
                }
            </li>

            <li class="phone-num">
                <i class="fa fa-phone"></i><span>
                    @{if (gym.Telemovel.Length != 9)
                        {
                            @gym.Telemovel.Substring(4, 9)
                        }
                        else
                        {
                            @gym.Telemovel
                        } }
                </span>
            </li>
        </ul>
    </header>

    <div>
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-text">
                        <div class="reserved">
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved
                        </div>
                        <div class="social-links">
                            <a href="https://www.facebook.com/neei.utad/"><i class="fab fa-facebook"></i></a>
                            <a href="https://www.instagram.com/neei.utad/?hl=pt"><i class="fab fa-instagram"></i></a>
                            <a href="https://twitter.com/7Andamos"><i class="fab fa-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <!-- Js Plugins -->
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.slicknav.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/circle-progress.min.js"></script>
    <script src="js/main.js"></script>
    <script>
        window.addEventListener("pageshow", function (event) {
            var historyTraversal = event.persisted ||
                (typeof window.performance != "undefined" &&
                    window.performance.navigation.type === 2);
            if (historyTraversal) {
                // Handle page restore.
                window.location.reload();
            }
        });
    </script>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthUp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/jqueryui/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }

        .topnav {
            overflow: hidden;
            background-color: #333;
        }

            .topnav a {
                float: left;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
                font-size: 17px;
            }

                .topnav a:hover {
                    background-color: #ddd;
                    color: black;
                }

                .topnav a.active {
                    background-color: #4CAF50;
                    color: white;
                }

        .topnav-right {
            float: right;
        }
    </style>
</head>
<body>
    <header>
        <div class="topnav">
            <a class="active" asp-controller="Home" asp-action="Index">Home</a>

            <a asp-controller="Home" asp-action="Privacy">Privacy</a>
            <a asp-controller="Utilizadores" asp-action="PlanoSemanal">Plano semanal de aulas</a>

            @if (Context.Session.GetString("Role") == "Admin")
            {
                <a asp-controller="Admins" asp-action="Index">Painel de gestão</a>
            }

            @if (Context.Session.GetString("Role") == "Socio")
            {
                <a asp-controller="Socios" asp-action="Index">Painel de sócios</a>
            }

            @if (Context.Session.GetString("Role") == "Professor")
            {
                <a asp-controller="Professores" asp-action="Index">Painel de professores</a>
            }

            <div class="topnav-right">

                @if (Context.Session.GetString("UserId") == null)
                {
                    <a asp-controller="Utilizadores" asp-action="PedidoSocio">Aderir ao HealthUp</a>
                }

                @if (Context.Session.GetString("UserId") == null)
                {
                    <a asp-controller="Utilizadores" asp-action="Login">Login</a>
                }
                else
                {
                    <a asp-controller="Utilizadores" asp-action="Logout">Logout</a>
                }
            </div>
        </div>
</header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HealthUp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>